apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp
  labels:
    app.kubernetes.io/name: guestbookapp
    app.kubernetes.io/component: frontendapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbookapp
      app.kubernetes.io/component: frontendapp
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbookapp
        app.kubernetes.io/component: frontendapp
    spec:
      containers:
      - name: guestbookapp
        image: paulczar/gb-frontend:v5
        
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80