apiVersion: v1
kind: PersistentVolume
metadata:
    name: pvstatic
    labels:
        type: localPV
spec:
    storageClassName: localstorage
    capacity:
      storage: 4Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/data/db"
      